# Sets default memory used for gradle commands. Can be overridden by user or command line properties.
# This is required to provide enough memory for the Minecraft decompilation process.
org.gradle.jvmargs=-Xmx4G
org.gradle.daemon=false
mod_version=1.5.5
mod_id=starbunclemania

minecraft_version=1.21.1
parchment_version=2024.07.28
minecraft_version_range=[1.21)
neo_version=21.1.210
neo_version_range=[21.0,)
loader_version_range=[2,)
ars_version=5.11.1.1275
nuggets_version=1.0.4.35
sauce_version=0.0.16.46
elemental_version=0.7.6.12.117
jei_version=19.21.0.247
geckolib_version=4.7.2
patchouli_version=87-NEOFORGE-SNAPSHOT
caelus_version=7.0.0+1.21
mekanism_version=10.7.13.78
eidolon_version=0.5.0.0-pre16.52

